# ref: https://docs.travis-ci.com/user/languages/python
language: python
dist: trusty
sudo: true
services:
  - docker

matrix:
    include:
     - python: 3.5
       env: TOXENV=py35
     - python: 3.5
       env: TOXENV=py35-functional
     - python: 3.6
       env: TOXENV=py36
     - python: 3.6
       env: TOXENV=py36-functional
     - python: 3.6
       env: TOXENV=update-pep8
     - python: 3.6
       env: TOXENV=docs
     - python: 3.6
       env: TOXENV=coverage,codecov
install:
  - pip install tox

script:
  - tox
