# ref: https://docs.travis-ci.com/user/languages/python
language: python
dist: trusty
sudo: true
services:
  - docker

matrix:
    include:
     - python: 3.5
       env: TOXENV=py35
     - python: 3.6
       env: TOXENV=py36

install:
  - pip install tox

script:
  - tox
